### PR TITLE
Remove tabs, update file and folder names

### PR DESCRIPTION
**Pull request by dthornton22**
Removing all tabs (there were not many).

By changing the file and folder naming scheme, this means that GitHub will display all files and folders in order (0, 1, 2, etc. and not 0, 1, 10, 2, etc.) Also fixed a few files that had lowercase "l" instead of uppercase "L" for lab in the file name.

### CODE REVIEW

**Comment by dthornton22** [comment]
Added readme cleanup

**Comment by dthornton22** [comment]
curly braces now have their own lines

**Comment by dthornton22** [comment]
All headers are standardized. Ready for review @uah-lacasa, @prawarpoudel

**Comment by prawarpoudel** [comment]
There are conflicts in some of the files, namely: 
 Lab10/Lab10_D1.c
Lab8/Lab8_D4.c
Lab9/Lab9_D1.c
README.md 

Can you please see and fix these? @dthornton22

**Review by prawarpoudel — APPROVED** [review]

**Review by prawarpoudel — APPROVED** [review]

**Review by prawarpoudel — APPROVED** [review]

**Review by prawarpoudel — CHANGES_REQUESTED** [review]
I will rather prefer the folder names to have Lab00_ instead of Lab_00 and so on.

**Review by prawarpoudel — CHANGES_REQUESTED** [review]
I will prefer file names to have Lab00_D0.c instead of Lab_00_D0.c.  (too many underscores)

**Review by prawarpoudel — APPROVED** [review]

**Review by prawarpoudel — APPROVED** [review]

**Comment by dthornton22** [comment]
Yes I will fix the underscores

**Pull request merged**
