### PR TITLE
Main

### PR DESCRIPTION
**Pull request by dthornton22**

### CODE REVIEW

**Comment by dthornton22** [comment]
@prawarpoudel I changed some variable and function names to be more descriptive. Also, the main change with this PR is comments and comment spacing. There were some minor README updates as well.

**Review by prawarpoudel — CHANGES_REQUESTED** [review]
file Lab01_D2.c, line 22 comment exponent should be greater than or equal to 1

**Comment by prawarpoudel** [comment]
I am not so sure about merging this. I may have to revisit previous merge as well when I have time. In the demo codes, the use of BIT0, 0x01, etc. for bit mask were done on purpose so that students get familiar with different notations. Changing all of them to uniform notation may not serve the purpose here.
@dthornton22 @uah-lacasa

**Review by prawarpoudel — APPROVED** [review]

**Comment by prawarpoudel** [comment]
I am accepting and merging, I may have to revisit later.

**Pull request merged**
