### PR TITLE
Demo Code Update

### PR DESCRIPTION
**Pull request by dthornton22**
The links in the README will only work if the pull request is accepted. All edits done by dht0002@uah.edu.

The way GitHub displays differences is not very friendly when renaming files. So, the best way to review these edits is to have the original file open and compare it to the corresponding file in this pull request. I would suggest using a tool such as [Notepad++](https://notepad-plus-plus.org/) and using the [compare](https://sourceforge.net/projects/npp-compare/) plugin. You can very easily utilize the open folder as workspace tool instead of having to go into the folders each time.

The biggest changes I made were to the header of each file, as well as whitespace clean up.

### CODE REVIEW

**Review by uah-lacasa — APPROVED** [review]

**Comment by dthornton22** [comment]
@uah-lacasa I think you still have to merge the pull request, not just approve it.

**Comment by uah-lacasa** [comment]
… they are no hold for now.

Some of your changes are breaking our rules –

e.g., machine instructions have to have suffix and it seems you removed them. 

Also, spaces have to be used instead of tabs, etc.

 

Dr. Aleksandar Milenkovic

Professor of Electrical and Computer Engineering

The University of Alabama in Huntsville

301 Sparkman Drive

Huntsville, AL 35899

Email:  <mailto:milenka@uah.edu> milenka@uah.edu

Web:  <https://www.ece.uah.edu/~milenka> https://www.ece.uah.edu/~milenka

Labs:  <https://lacasa.uah.edu/> https://lacasa.uah.edu,  <https://portal.mhealth.uah.edu/> https://portal.mhealth.uah.edu

**Comment by dthornton22** [comment]
Since there was a mix of tabs and spaces, I didn't know you wanted only spaces. I am happy to make this change.

**Comment by dthornton22** [comment]
I am going to close this pull request for now. I will make smaller changes and multiple pull requests so it is easier to see my changes.

**Pull request closed without merging**
